// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/ghaidafasya24",
            "email": "714220031@std.ulbi.ac.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/kategori": {
            "get": {
                "description": "Mengambil semua data kategori koleksi",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kategori"
                ],
                "summary": "Get All Kategori",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menambahkan data kategori museum menggunakan form-data (wajib token)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kategori"
                ],
                "summary": "Insert Kategori",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nama kategori",
                        "name": "nama_kategori",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deskripsi kategori",
                        "name": "deskripsi",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/kategori/{id}": {
            "get": {
                "description": "Mengambil satu data kategori koleksi berdasarkan ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kategori"
                ],
                "summary": "Get Kategori by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Kategori",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengubah data kategori berdasarkan ID. Endpoint ini memerlukan autentikasi JWT Bearer dan menggunakan form-data.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kategori"
                ],
                "summary": "Update Kategori",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Kategori",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nama kategori",
                        "name": "nama_kategori",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deskripsi kategori",
                        "name": "deskripsi",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Kategori berhasil diperbarui",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus data kategori berdasarkan ID (wajib autentikasi JWT Bearer)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kategori"
                ],
                "summary": "Delete Kategori",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID kategori",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Kategori berhasil dihapus",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/koleksi": {
            "get": {
                "description": "Mengambil semua data koleksi museum beserta kategori, tempat penyimpanan, dan ukuran",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Koleksi"
                ],
                "summary": "Get All Koleksi",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menambahkan data koleksi museum baru, termasuk kategori, gudang, rak, tahap, dan foto. File foto diupload menggunakan form-data.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Koleksi"
                ],
                "summary": "Insert Koleksi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nomor Registrasi",
                        "name": "no_reg",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nomor Inventaris",
                        "name": "no_inv",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nama Benda",
                        "name": "nama_benda",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tanggal Perolehan (format: YYYY-MM-DD)",
                        "name": "tanggal_perolehan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ID Kategori (MongoDB ObjectID)",
                        "name": "kategori_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bahan Benda",
                        "name": "bahan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Panjang Keseluruhan (ukuran)",
                        "name": "panjang_keseluruhan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Lebar (ukuran)",
                        "name": "lebar",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tebal (ukuran)",
                        "name": "tebal",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tinggi (ukuran)",
                        "name": "tinggi",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Diameter (ukuran)",
                        "name": "diameter",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Berat (ukuran)",
                        "name": "berat",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Satuan ukuran panjang",
                        "name": "satuan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Satuan berat",
                        "name": "satuan_berat",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Asal Koleksi",
                        "name": "asal_koleksi",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tempat Perolehan",
                        "name": "tempat_perolehan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Deskripsi Koleksi",
                        "name": "deskripsi",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ID Gudang (MongoDB ObjectID)",
                        "name": "gudang_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID Rak (MongoDB ObjectID)",
                        "name": "rak_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ID Tahap (MongoDB ObjectID)",
                        "name": "tahap_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Kondisi Koleksi",
                        "name": "kondisi",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Upload foto koleksi",
                        "name": "foto",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Koleksi berhasil disimpan",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/koleksi/{id}": {
            "get": {
                "description": "Mengambil satu data koleksi museum berdasarkan ID MongoDB",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Koleksi"
                ],
                "summary": "Get Koleksi By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Koleksi",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memperbarui data koleksi museum berdasarkan ID. Semua field bersifat opsional, kecuali \"gudang_id\" wajib diisi. Jika foto diupload, akan mengganti foto lama.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Koleksi"
                ],
                "summary": "Update Koleksi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Koleksi (MongoDB ObjectID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nomor Registrasi",
                        "name": "no_reg",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Nomor Inventaris",
                        "name": "no_inv",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Nama Benda",
                        "name": "nama_benda",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tanggal Perolehan (format: YYYY-MM-DD)",
                        "name": "tanggal_perolehan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ID Kategori (MongoDB ObjectID)",
                        "name": "kategori_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Bahan Benda",
                        "name": "bahan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Panjang Keseluruhan (ukuran)",
                        "name": "panjang_keseluruhan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Lebar (ukuran)",
                        "name": "lebar",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tebal (ukuran)",
                        "name": "tebal",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tinggi (ukuran)",
                        "name": "tinggi",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Diameter (ukuran)",
                        "name": "diameter",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Berat (ukuran)",
                        "name": "berat",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Satuan ukuran panjang",
                        "name": "satuan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Satuan berat",
                        "name": "satuan_berat",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Asal Koleksi",
                        "name": "asal_koleksi",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tempat Perolehan",
                        "name": "tempat_perolehan",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Deskripsi Koleksi",
                        "name": "deskripsi",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ID Gudang (MongoDB ObjectID)",
                        "name": "gudang_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID Rak (MongoDB ObjectID)",
                        "name": "rak_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "ID Tahap (MongoDB ObjectID)",
                        "name": "tahap_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Kondisi Koleksi",
                        "name": "kondisi",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Upload foto koleksi (opsional, mengganti foto lama)",
                        "name": "foto",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Koleksi berhasil diperbarui",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus data koleksi berdasarkan ID (wajib autentikasi JWT Bearer)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Koleksi"
                ],
                "summary": "Delete Koleksi by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID koleksi",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/users": {
            "get": {
                "description": "Endpoint untuk mengambil seluruh data admin yang tersimpan di sistem",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get All Users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetAllUsersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Autentikasi user menggunakan username dan password, kemudian mengembalikan JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Data login user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Users"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Registrasi akun admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "Payload Body [RAW]",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Users"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/username/{username}": {
            "get": {
                "description": "Mengambil data detail user berdasarkan username tertentu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get User by Username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetAllUsersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Mengambil data user berdasarkan ID MongoDB",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get User by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User berhasil ditampilkan",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memperbarui data user berdasarkan ID (wajib autentikasi JWT Bearer)",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID user",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username (huruf kecil semua)",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Nomor telepon format 62xxxxxxxx",
                        "name": "phone_number",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Password baru",
                        "name": "password",
                        "in": "formData"
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus data user berdasarkan ID (wajib autentikasi JWT Bearer)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID user",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User berhasil dihapus",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.GetAllUsersResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Users"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Berhasil mengambil semua data users"
                },
                "total": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "admin12345"
                },
                "username": {
                    "type": "string",
                    "example": "ghaida"
                }
            }
        },
        "model.RegisterRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "admin12345"
                },
                "phone_number": {
                    "type": "string",
                    "example": "6281234567890"
                },
                "username": {
                    "type": "string",
                    "example": "ghaida"
                }
            }
        },
        "model.Users": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string",
                    "example": "12345678"
                },
                "phone_number": {
                    "type": "string",
                    "example": "6281234567890"
                },
                "role": {
                    "type": "string",
                    "example": "admin"
                },
                "username": {
                    "type": "string",
                    "example": "ghaida"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Masukkan token dengan format: Bearer \u003cJWT Token\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "inventorymuseum-de54c3e9b901.herokuapp.com",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "API Pengelolaan Gudang Koleksi Museum",
	Description:      "Dokumentasi API untuk sistem pengelolaan museum",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
